Repository BrighterCommand/Brighter, pull requests merged in 2021-05, with the labels that each got.

#1510 Fix DeSeralisation Issues around Message and MessageBody #1509
  src/Paramore.Brighter.ServiceActivator/MessagePump.cs
  src/Paramore.Brighter/Message.cs
  src/Paramore.Brighter/MessageBody.cs
  src/Paramore.Brighter/MessageHeader.cs
  src/Paramore.Brighter/PostBackItem.cs
  tests/Paramore.Brighter.Core.Tests/MessageSerilisation/MessageSerilisationTests.cs
Labels: 2 - In Progress, Bug

#1494 Support Publisher Confirms from RMQ
  samples/RMQTaskQueueSamples/GreetingsSender/Program.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessagePublisher.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqPublication.cs
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/Publication.cs
  tests/Paramore.Brighter.RMQ.Tests/MessagingGateway/When_confirming_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Tests/MessagingGateway/When_confirming_posting_a_message_via_the_messaging_gateway_async.cs
Labels: 3 - Done, feature request

#1522 Breaking out the tests again
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/When_a_message_dispatcher_has_a_new_connection_added_while_running.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/When_a_message_dispatcher_restarts_a_connection.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/When_a_message_dispatcher_restarts_a_connection_after_all_connections_have_stopped.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/When_a_requeue_count_threshold_for_commands_has_been_reached.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/When_a_requeue_count_threshold_for_events_has_been_reached.cs
Labels: 2 - In Progress, Bug

#1548 Fix red tests
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Inbox_Enabled.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Inbox_Enabled_Async.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Throw_Enabled.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Throw_Enabled_Async.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Warn_Enabled.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_Once_Only_With_Warn_Enabled_Async.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_With_A_Inbox_Enabled.cs
  tests/Paramore.Brighter.Core.Tests/OnceOnly/When_Handling_A_Command_With_A_Inbox_Enabled_Async.cs
Labels: Bug

#1556 Use topic from message header, allow send to multiple topics
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsPublication.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_a_message_consumer_reads_multiple_messages.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_assume.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_verify.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_verify_by_arn.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_verify_by_convention.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_queues_missing_assume_throws.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_queues_missing_verify_throws.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_rejecting_a_message_through_gateway_with_requeue.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_requeueing_a_message.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_requeueing_redrives_to_the_dlq.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_topic_missing_verify_throws.cs
Labels: 3 - Done, Bug
