Repository BrighterCommand/Brighter, pull requests merged in 2021-03, with the labels that each got.

#1438 Initial commit to support Azure Service Bus
  Brighter.sln
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducerFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessagingGatewayConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusSubscription.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/BrokeredMessageWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/IBrokeredMessageWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/IManagementClientWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/IMessageReceiverProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/IMessageReceiverWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/ITopicClient.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/ITopicClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/ManagementClientWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/MessageReceiverProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/MessageReceiverWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/TopicClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/TopicClientWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/MessageGateway.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/MessageSenderPool.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/Paramore.Brighter.MessagingGateway.AzureServiceBus.csproj
  tests/Paramore.Brighter.AzureServiceBus.Tests/AzureServiceBusChannelFactoryTests.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/AzureServiceBusConsumerTests.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/AzureServiceBusMessageProducerTests.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/Paramore.Brighter.AzureServiceBus.Tests.csproj
Labels: 2 - In Progress, feature request, grabbed by community

#1449 Check if Topic Exists before creation Subscription #1444
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/ManagementClientWrapper.cs
Labels: 3 - Done, Bug

#1448 Fix message parse failed issue with AWS SQS
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageCreator.cs
Labels: 3 - Done, Bug

#1458 Plumbed Channel Creation Mode into the Factories #1444
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducerFactory.cs
Labels: 3 - Done, grabbed by assignee

#1427 Fix some issues with AWS (failing tests and TopicARN validation)
  Brighter.sln
  samples/AWSTaskQueueSamples/GreetingsReceiverConsole/Program.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSMessagingGateway.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_a_message_consumer_reads_multiple_messages.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_assume.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_infastructure_exists_can_verify.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_queues_missing_assume_throws.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_queues_missing_verify_throws.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_rejecting_a_message_through_gateway_with_requeue.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_requeueing_a_message.cs
  tests/Paramore.Brighter.AWSSQS.Tests/MessagingGateway/When_topic_missing_verify_throws.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_assumes_topic_but_missing_on_a_confluent_cluster.cs
Labels: 3 - Done, Bug, grabbed by assignee

#1473 Only run the Kafka tests locally to see if issues are Confluent
  .github/workflows/ci.yml
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_message_is_acknowledged_update_offset.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_set_of_messages_is_sent_preserve_order.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_set_of_messages_is_sent_preserve_order_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_assumes_topic_but_missing_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_declares_topic.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_declares_topic_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_offsets_awaiting_next_acknowledge_sweep_them.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_posting_a_message_to_a_confluent_cluster.cs
Labels: 3 - Done, Bug
