Repository BrighterCommand/Brighter, pull requests merged in 2022-10, with the labels that each got.

#2264 Intial Plumb in of Bulk Deposit Async
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MsSql/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutboxSync.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutboxSync.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutboxSync.cs
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/CommandProcessorBuilder.cs
  src/Paramore.Brighter/ExternalBusConfiguration.cs
  src/Paramore.Brighter/ExternalBusServices.cs
  src/Paramore.Brighter/IAmABulkOutboxAsync.cs
  src/Paramore.Brighter/IAmABulkOutboxSync.cs
  src/Paramore.Brighter/InMemoryOutbox.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/FakeOutboxSync.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/When_Depositing_A_Message_In_The_Message_StoreAsync_Bulk.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/When_Depositing_A_Message_In_The_Message_Store_Bulk.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_messages_to_the_message_store.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_messages_to_the_message_store_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_messages_to_the_outbox.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_messages_to_the_outbox_async.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_Writing_Messages_To_The_Outbox.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_Writing_Messages_To_The_Outbox.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_Writing_Messages_To_The_Outbox_Async.cs
Labels: 2 - In Progress, feature request

#2300 Examples should show Darker attributes too
  samples/WebAPI_Dapper/GreetingsPorts/Handlers/FIndGreetingsForPersonHandlerAsync.cs
  samples/WebAPI_Dapper/GreetingsPorts/Handlers/FindPersonByNameHandlerAsync.cs
  samples/WebAPI_Dapper/GreetingsWeb/GreetingsWeb.csproj
  samples/WebAPI_Dapper/GreetingsWeb/Startup.cs
  samples/WebAPI_Dynamo/GreetingsPorts/GreetingsPorts.csproj
  samples/WebAPI_Dynamo/GreetingsPorts/Handlers/FIndGreetingsForPersonHandlerAsync.cs
  samples/WebAPI_Dynamo/GreetingsPorts/Handlers/FindPersonByNameHandlerAsync.cs
  samples/WebAPI_Dynamo/GreetingsWeb/GreetingsWeb.csproj
  samples/WebAPI_Dynamo/GreetingsWeb/Startup.cs
  samples/WebAPI_EFCore/GreetingsPorts/GreetingsPorts.csproj
  samples/WebAPI_EFCore/GreetingsPorts/Handlers/FIndGreetingsForPersonHandlerAsync.cs
  samples/WebAPI_EFCore/GreetingsPorts/Handlers/FindPersonByNameHandlerAsync.cs
Labels: 3 - Done, Documentation Error

#2316 Handle Null message Bodies in the outbox #2235
  samples/OpenTelemetry/Consumer/Properties/launchSettings.json
  samples/OpenTelemetry/Sweeper/Properties/launchSettings.json
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_a_message_to_the_message_store.cs
Labels: 2 - In Progress, Bug
