Repository BrighterCommand/Brighter, pull requests merged in 2023-04, with the labels that each got.

#2563 remove redundant .GetTypeInfo()
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionBrighterBuilder.cs
  src/Paramore.Brighter/Extensions/ReflectionExtensions.cs
  src/Paramore.Brighter/PipelineBuilder.cs
  src/Paramore.Brighter/RequestHandler.cs
  src/Paramore.Brighter/RequestHandlerAsync.cs
  src/Paramore.Brighter/TransformPipelineBuilder.cs
Labels: 3 - Done

#2586 pass cancellation token
  samples/ASBTaskQueue/Greetings/Ports/CommandHandlers/AddGreetingCommandHandler.cs
  samples/ASBTaskQueue/Greetings/Ports/CommandHandlers/GreetingEventAsyncHandler.cs
  samples/HelloAsyncListeners/IpFyApi.cs
  samples/HelloWorldAsync/IpFyApi.cs
  samples/WebAPI_Dynamo/GreetingsPorts/Handlers/AddGreetingHandlerAsync.cs
  samples/WebAPI_Dynamo/GreetingsPorts/Handlers/FindPersonByNameHandlerAsync.cs
  src/Paramore.Brighter.DynamoDb/DynamoDbTableBuilder.cs
  src/Paramore.Brighter/ExternalBusServices.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/MyEventHandlerAsyncWithContinuation.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/FakeCommandProcessor.cs
Labels: 3 - Done

#2587 fix broken comments
  src/Paramore.Brighter.ServiceActivator/DispatchBuilder.cs
Labels: 3 - Done

#2591 fix typo in TimeoutInMilliseconds
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusChannelFactory.cs
  src/Paramore.Brighter.ServiceActivator/ConsumerFactory.cs
  src/Paramore.Brighter/Subscription.cs
Labels: 2 - In Progress

#2593 Add Options and Tagging to the Archive provider
  Brighter.sln
  src/Paramore.Brighter.Archive.Azure/AzureBlobArchiveProvider.cs
  src/Paramore.Brighter.Archive.Azure/AzureBlobArchiveProviderOptions.cs
  tests/Paramore.Brighter.Azure.Tests/AzureBlobArchiveProviderTests.cs
Labels: 3 - Done, feature request

#2628 Kafka Missing Headers and Partition Key
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageProducer.cs
  src/Paramore.Brighter/Policies/Handlers/ExceptionPolicyHandlerAsync.cs
  tests/Paramore.Brighter.Core.Tests/ExceptionPolicy/TestDoubles/MyMultiplePoliciesFailsWithDivideByZeroHandlerAsync.cs
  tests/Paramore.Brighter.Core.Tests/ExceptionPolicy/When_Sending_A_Command_That_Retries_Then_Repeatedly_Fails_Breaks_The_Circuit_Async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_posting_a_message.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_recieving_a_message_without_partition_key_header.cs
Labels: 3 - Done, Bug
