Repository BrighterCommand/Brighter, pull requests merged in 2024-02, with the labels that each got.

#3008 Inbox Configuration was not being handled
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.ServiceActivator.Extensions.DependencyInjection/ServiceActivatorOptions.cs
  src/Paramore.Brighter/CommandProcessorBuilder.cs
  src/Paramore.Brighter/IServiceActivatorOptions.cs
  src/Paramore.Brighter/InMemoryOutbox.cs
  src/Paramore.Brighter/InboxConfiguration.cs
  src/Paramore.Brighter/RelationalDbTransactionProvider.cs
Labels: 3 - Done, Bug

#3010 [Docs]Add Some More ADRs to describe old decisions
  docs/adr/0002-use-a-single-threaded-message-pump.md
  docs/adr/0003-use-claim-check-for-large-messages.md
  docs/adr/0004-use-an-envelope-wrapper-with-transports.md
  docs/adr/0006-blocking-and-non-blocking-retries.md
  docs/adr/0007-aspect-oriented-programming.md
Labels: Documentation Error

#2733 An assortment of minor docs and spelling fixes
  README.md
  samples/ASBTaskQueue/Greetings/Adaptors/Services/UnitOfWork.cs
  src/Paramore.Brighter.DynamoDb/DynamoDbTableBuilder.cs
  src/Paramore.Brighter.DynamoDb/DynamoDbTableFactory.cs
  src/Paramore.Brighter.DynamoDb/GUIDConverter.cs
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionMessageMapperRegistry.cs
  src/Paramore.Brighter.Inbox.DynamoDB/DynamoDbInbox.cs
  src/Paramore.Brighter.Inbox.MySql/MySqlInboxBuilder.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumer.cs
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter.ServiceActivator.Extensions.Diagnostics/HealthChecks/BrighterServiceActivatorHealthCheck.cs
  src/Paramore.Brighter.ServiceActivator/Dispatcher.cs
  src/Paramore.Brighter.ServiceActivator/TestHelpers/FakeChannel.cs
  src/Paramore.Brighter/AsyncHandlerFactory.cs
  src/Paramore.Brighter/Channel.cs
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/ControlBusSender.cs
  src/Paramore.Brighter/ControlBusSenderFactory.cs
  src/Paramore.Brighter/FeatureSwitch/Attributes/FeatureSwitchAttribute.cs
  src/Paramore.Brighter/IAmAChannel.cs
  src/Paramore.Brighter/IAmAChannelFactory.cs
  src/Paramore.Brighter/IAmACommandProcessor.cs
  src/Paramore.Brighter/IAmAMessageTransformerFactory.cs
  src/Paramore.Brighter/IAmAnArchiveProvider.cs
  src/Paramore.Brighter/Logging/Handlers/RequestLoggingHandler.cs
  src/Paramore.Brighter/MessageHeader.cs
  src/Paramore.Brighter/Subscription.cs
  src/Paramore.Brighter/TransformAttributeBase.cs
  src/Paramore.Brighter/TransformPipelineBuilder.cs
  src/Paramore.Brighter/Transforms/Transformers/ClaimCheckTransformer.cs
  src/Paramore.Brighter/UnwrapPipeline.cs
  src/Paramore.Brighter/WrapPipeline.cs
  tests/Paramore.Brighter.Core.Tests/Paramore.Brighter.Core.Tests.csproj
Labels: 2 - In Progress, Bug, Documentation Error
