Repository BrighterCommand/Brighter, pull requests merged in 2024-07, with the labels that each got.

#3181 Use Default Synchronization Context
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/ControlBusSender.cs
  src/Paramore.Brighter/ExternalBusService.cs
  src/Paramore.Brighter/IAmACommandProcessor.cs
  src/Paramore.Brighter/IAmAControlBusSender.cs
  src/Paramore.Brighter/IAmAnExternalBusService.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/TestDoubles/SpyCommandProcessor.cs
  tests/Paramore.Brighter.Core.Tests/Monitoring/TestDoubles/SpyControlBusSender.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/FakeCommandProcessor.cs
Labels: 3 - Done, Breaking Change, feature request, v10, .NET

#3182 [Feature] Parallel Publish
  docs/adr/0013-publish-should-be-in-parallel.md
  src/Paramore.Brighter.ServiceActivator/MessagePump.cs
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/FeatureSwitch/Providers/FluentConfigRegistry.cs
  src/Paramore.Brighter/IRequestContext.cs
  src/Paramore.Brighter/Policies/Handlers/FallbackPolicyHandler.cs
  src/Paramore.Brighter/Policies/Handlers/FallbackPolicyHandlerRequestHandlerAsync.cs
  src/Paramore.Brighter/RequestContext.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/MyOtherEventHandler.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/When_A_Request_Context_Is_Provided.cs
  tests/Paramore.Brighter.Core.Tests/Context/When_Accessing_A_Request_Context.cs
  tests/Paramore.Brighter.Core.Tests/Context/When_Creating_A_Request_Context.cs
  tests/Paramore.Brighter.Core.Tests/ExceptionPolicy/When_Sending_A_Command_That_Retries_Then_Repeatedly_Fails_Breaks_The_Circuit.cs
  tests/Paramore.Brighter.Core.Tests/ExceptionPolicy/When_Sending_A_Command_That_Retries_Then_Repeatedly_Fails_Breaks_The_Circuit_Async.cs
  tests/Paramore.Brighter.Core.Tests/Locking/When_Lock_Is_Called_It_Can_Only_Be_Obtained_Once.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_A_Stop_Message_Is_Added_To_A_Channel.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_Acknowledge_Is_Called_On_A_Channel.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_Listening_To_Messages_On_A_Channel.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_No_Acknowledge_Is_Called_On_A_Channel.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_Requeuing_A_Message_With_No_Delay.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_The_Buffer_Is_Not_Empty_Read_From_That_Before_Receiving.cs
  tests/Paramore.Brighter.Core.Tests/Observability/CommandProcessor/Publish/When_Publishing_A_Request_A_Span_Is_Exported.cs
  tests/Paramore.Brighter.Extensions.Tests/TestDifferentSetups.cs
Labels: 3 - Done, Breaking Change, feature request, v10, .NET

#3195 Ensure that we dont recreate Service Bus clients on every get
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/IServiceBusSenderWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusWrappers/ServiceBusSenderWrapper.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusChainedClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusConnectionStringClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusDefaultAzureClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusManagedIdentityClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusVisualStudioCredentialClientProvider.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/AzureServiceBusChannelFactoryTests.cs
Labels: 3 - Done, Bug, v9, .NET

#3184 Backport customisable AWS SDK clients to v9
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSClientFactory.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSMessagingGateway.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSMessagingGatewayConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByArn.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByArnConvention.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByName.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/InterceptingDelegatingHandler.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/InterceptingHttpClientFactory.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/When_customising_aws_client_config.cs
Labels: 3 - Done, feature request, v9, .NET

#3114 Add support for customising AWS SDK client config
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSClientFactory.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSMessagingGateway.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/AWSMessagingGatewayConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByArn.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByArnConvention.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ValidateTopicByName.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/InterceptingDelegatingHandler.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/InterceptingHttpClientFactory.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/When_customising_aws_client_config.cs
Labels: 3 - Done, feature request, v10, .NET

#3107 Add support for Postgres Locking
  Brighter.sln
  src/Paramore.Brighter.Locking.PostgresSql/Paramore.Brighter.Locking.PostgresSql.csproj
  src/Paramore.Brighter.Locking.PostgresSql/PostgresLockingProvider.cs
  src/Paramore.Brighter.Locking.PostgresSql/PostgresLockingProviderOptions.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Paramore.Brighter.PostgresSQL.Tests.csproj
  tests/Paramore.Brighter.PostgresSQL.Tests/PostgresLockingProviderTest.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/PostgresSqlTestHelper.cs
Labels: 2 - In Progress, grabbed by community, feature request, v10, .NET
