Repository BrighterCommand/Brighter, pull requests merged in 2024-09, with the labels that each got.

#3296 Implement sparse outstanding index for dynamo DB outbox [v10]
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter.Outbox.DynamoDB/KeyTopicOutstandingCreatedTimeExpression.cs
  src/Paramore.Brighter.Outbox.DynamoDB/MessageItem.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/When_there_are_outstanding_messages_in_the_outbox.cs
Labels: 3 - Done, v10

#3298 Fixes around datetime and outboxes in V10
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.Outbox.DynamoDB/MessageItem.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
  src/Paramore.Brighter/ExternalBusService.cs
  src/Paramore.Brighter/InMemoryBox.cs
  src/Paramore.Brighter/InMemoryOutbox.cs
  src/Paramore.Brighter/MessageHeader.cs
  tests/Paramore.Brighter.Core.Tests/Archiving/When_Archiving_Old_Messages_From_The_Outbox.cs
  tests/Paramore.Brighter.Core.Tests/Archiving/When_Archiving_Old_Messages_From_The_Outbox_Async.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_Via_A_Control_Bus_Sender.cs
  tests/Paramore.Brighter.InMemory.Tests/Outbox/When_storing_message_in_outbox.cs
  tests/Paramore.Brighter.InMemory.Tests/Sweeper/When_sweeping_the_outbox.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/FakeCommandProcessor.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/MessageExtensions.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/MyEvent.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/MyEventMessageMapper.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/MyEventMessageMapperAsync.cs
Labels: 3 - Done, Bug, v10, .NET, Draft

#3205 [Chore] Add ADRs to explain existing decisions
  docs/adr/0002-use-a-single-threaded-message-pump.md
  docs/adr/0003-use-claim-check-for-large-messages.md
  docs/adr/0004-use-an-envelope-wrapper-with-transports.md
  docs/adr/0005-support-async-pipelines.md
  docs/adr/0006-blocking-and-non-blocking-retries.md
  docs/adr/0007-aspect-oriented-programming.md
  docs/adr/0008-support-cloud-events.md
  docs/adr/0009-expose-request-context.md
  docs/adr/0010-brighter-semantic-conventions.md
  docs/adr/0011-brighter-support-for-bulk-messaging-operations.md
  docs/adr/0012-provide-in-memory-and-simple-implementations.md
  docs/adr/0013-publish-should-be-in-parallel.md
  docs/adr/0014-di-friendly-framework.md
  docs/adr/0015-push-button-api-for-dsl.md
  docs/adr/0016-use-configuration-as-code-not-by-convention.md
  docs/adr/0017-use-strict-cqs-across-brighter-and-darker.md
  docs/adr/0018-support-a-command-oriented-interface.md
  docs/adr/0019-avoid-primitive-obsession.md
Labels: 2 - In Progress, feature request, Draft, Documentation

#3335 [Fix] Redis test failing, needs to check value
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/When_parsing_a_good_redis_message_to_brighter.cs
Labels: 3 - Done, Bug, v10, .NET
