Repository BrighterCommand/Brighter, pull requests merged in 2025-01, with the labels that each got.

#3452 fix: incorrect number of operationstartedcalls
  src/Paramore.Brighter.DynamoDb/DynamoDbUnitOfWork.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/ChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusQueueConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusTopicConsumer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessagingGateway.cs
  src/Paramore.Brighter.MessagingGateway.MQTT/MQTTMessagePublisher.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessageGatewayConnectionPool.cs
  src/Paramore.Brighter.MessagingGateway.RMQ/RmqMessageProducer.cs
  src/Paramore.Brighter.ServiceActivator/Proactor.cs
  src/Paramore.Brighter/Tasks/BrighterAsyncContext.cs
  src/Paramore.Brighter/Tasks/BrighterSynchronizationContext.cs
  src/Paramore.Brighter/Tasks/BrighterSynchronizationContextScope.cs
  src/Paramore.Brighter/Tasks/BrighterTaskQueue.cs
  src/Paramore.Brighter/Tasks/BrighterTaskScheduler.cs
  src/Paramore.Brighter/Tasks/TaskExtensions.cs
  src/Paramore.Brighter/Tasks/TaskFactoryExtensions.cs
  tests/Paramore.Brighter.Core.Tests/Tasks/BrighterSynchronizationContextsTests.cs
Labels: 3 - Done, Bug, v10, .NET

#3447 Fixes for Kafka Tests following the Proactor/Reactor split
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaDefaultMessageHeaderBuilder.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessagePublisher.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_a_message_is_acknowledged_update_offset_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_a_set_of_messages_is_sent_preserve_order_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_consumer_assumes_topic_but_missing_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_consumer_declares_topic_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_offsets_awaiting_next_acknowledge_sweep_them_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_posting_a_message_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_posting_a_message_with_header_bytes_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_recieving_a_message_without_partition_key_header_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_a_message_is_acknowledged_update_offset.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_a_set_of_messages_is_sent_preserve_order.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_consumer_assumes_topic_but_missing.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_consumer_declares_topic.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_converting_brighterheader_to_kafkaheader.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_converting_kafkaheader_to_brighterheader.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_offsets_awaiting_next_acknowledge_sweep_them.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_posting_a_message.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_posting_a_message_with_header_bytes.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_recieving_a_message_without_partition_key_header.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_message_is_acknowledged_update_offset.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_set_of_messages_is_sent_preserve_order_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_a_set_of_messages_is_sent_preserve_order_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_assumes_topic_but_missing_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_assumes_topic_but_missing_on_a_confluent_cluster_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_declares_topic_on_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_consumer_declares_topic_on_a_confluent_cluster_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_posting_a_message_to_a_confluent_cluster.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_posting_a_message_to_a_confluent_cluster_async.cs
Labels: 2 - In Progress, Bug, v10, .NET

#3489 Fix ASB Transport Tests for V10
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusQueueConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusSubscription.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusSubscriptionConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusTopicConsumer.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusAzureCliCredentialClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusChainedClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusConnectionStringClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusDefaultAzureClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusManagedIdentityClientProvider.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/ClientProvider/ServiceBusVisualStudioCredentialClientProvider.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/AzureServiceBusChannelFactoryTests.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/MessagingGateway/Proactor/AzureServiceBusConsumerTestsAsync.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/MessagingGateway/Proactor/AzureServiceBusMessageProducerTestsAsync.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/MessagingGateway/Reactor/AzureServiceBusConsumerTests.cs
  tests/Paramore.Brighter.AzureServiceBus.Tests/MessagingGateway/Reactor/AzureServiceBusMessageProducerTests.cs
Labels: 3 - Done, v10
