Repository BrighterCommand/Brighter, pull requests merged in 2025-02, with the labels that each got.

#3518 Redis fixes
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageGateway.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_a_message_consumer_throws_a_socket_exception_when_connecting_to_the_server_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_a_message_consumer_throws_a_timeout_exception_when_connecting_to_the_pool_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_posting_a_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_posting_multiple_messages_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_requeing_a_failed_message_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Proactor/When_requeing_a_failed_message_with_delay_async.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_a_message_consumer_throws_a_socket_exception_when_connecting_to_the_server.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_a_message_consumer_throws_a_timeout_exception_when_connecting_to_the_pool.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_posting_multiple_messages_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_requeing_a_failed_message.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/Reactor/When_requeing_a_failed_message_with_delay.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/RedisFixture.cs
  tests/Paramore.Brighter.Redis.Tests/TestDoubles/RedisMessageConsumerSocketErrorOnGetClient.cs
  tests/Paramore.Brighter.Redis.Tests/TestDoubles/RedisMessageConsumerTimeoutOnGetClient.cs
Labels: 3 - Done, grabbed by assignee, feature request, v10, .NET

#3520 Mqtt fixes
  Directory.Packages.props
  src/Paramore.Brighter.MessagingGateway.MQTT/MQTTMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.MQTT/MQTTMessagePublisher.cs
  src/Paramore.Brighter.MessagingGateway.MQTT/Paramore.Brighter.MessagingGateway.MQTT.csproj
  tests/Paramore.Brighter.MQTT.Tests/MessagingGateway/Proactor/When_posting_multiples_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.MQTT.Tests/MessagingGateway/Proactor/When_queue_is_purged_async.cs
  tests/Paramore.Brighter.MQTT.Tests/MessagingGateway/Reactor/When_posting_multiples_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.MQTT.Tests/MessagingGateway/Reactor/When_queue_is_purged.cs
Labels: 3 - Done, grabbed by assignee, dependencies, v10, .NET

#3396 Add support to MySQL for distributed lock
  Brighter.sln
  src/Paramore.Brighter.Locking.MySql/MySqlLockingProvider.cs
  src/Paramore.Brighter.Locking.MySql/MySqlLockingQueries.cs
  src/Paramore.Brighter.Locking.MySql/Paramore.Brighter.Locking.MySql.csproj
  tests/Paramore.Brighter.MySQL.Tests/LockingProvider/MySqlLockingProviderTests.cs
  tests/Paramore.Brighter.MySQL.Tests/MySqlTestHelper.cs
  tests/Paramore.Brighter.MySQL.Tests/Paramore.Brighter.MySQL.Tests.csproj
Labels: 2 - In Progress, v10, Draft
