Repository BrighterCommand/Brighter, pull requests merged in 2025-07, with the labels that each got.

#3637 (Agent) Friendly Contrib
  Contributing.md
  tests/README.md
Labels: 2 - In Progress, feature request, Documentation, Agent Friendly

#3642 Quorum Queues Tests Fix
  docker-compose-rmq.yaml
  src/Paramore.Brighter/MessageHeader.cs
  tests/Paramore.Brighter.RMQ.Async.Tests/MessagingGateway/Proactor/When_creating_quorum_queue_validation.cs
  tests/Paramore.Brighter.RMQ.Async.Tests/MessagingGateway/Proactor/When_posting_a_message_via_the_messaging_gateway_quorum_async.cs
  tests/Paramore.Brighter.RMQ.Async.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Async.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway_quorum.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_a_message_consumer_reads_multiple_messages.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_binding_a_channel_to_multiple_topics.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_confirming_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_infrastructure_exists_can_assert.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_infrastructure_exists_can_validate.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_posting_a_message_to_persist_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/Reactor/When_reading_a_delayed_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RMQ.Sync.Tests/MessagingGateway/TestHelpers.cs
Labels: 3 - Done, v10, .NET

#3666 feat: Allow SqsPublication set QueueAttribute and channel type
  src/Paramore.Brighter.MessagingGateway.AWS.V4/SqsPublication.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsPublication.cs
  src/Paramore.Brighter/ChannelName.cs
  tests/Paramore.Brighter.AWSScheduler.Tests/Scheduler/Requests/Sqs/When_Scheduling_A_Sqs_Request_Async.cs
  tests/Paramore.Brighter.AWSScheduler.V4.Tests/Scheduler/Requests/Sqs/When_Scheduling_A_Sqs_Request_Async.cs
Labels: 2 - In Progress, Bug, v10, .NET

#3634 [Feature] Create Adaptors for other messaging integration
  .github/workflows/ci.yml
  Brighter.sln
  Directory.Packages.props
  samples/Transforms/JustSaying/BrighterSide/BrighterSide.csproj
  samples/Transforms/JustSaying/BrighterSide/Program.cs
  samples/Transforms/JustSaying/JustSayingSide/JustSayingSide.csproj
  samples/Transforms/JustSaying/JustSayingSide/Program.cs
  samples/Transforms/MassTransit/MBrigtherSide/MBrigtherSide.csproj
  samples/Transforms/MassTransit/MBrigtherSide/Program.cs
  samples/Transforms/MassTransit/MassTransitSide/MassTransitSide.csproj
  samples/Transforms/MassTransit/MassTransitSide/Program.cs
  src/Paramore.Brighter.MessagingGateway.AWS.V4/SqsInlineMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.AWS.V4/SqsMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsInlineMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.RMQ.Async/RmqMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.RMQ.Sync/RmqMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageCreator.cs
  src/Paramore.Brighter.Transformers.JustSaying/Extensions/JsonNodeExtensions.cs
  src/Paramore.Brighter.Transformers.JustSaying/Extensions/RequestContextExtensions.cs
  src/Paramore.Brighter.Transformers.JustSaying/IJustSayingRequest.cs
  src/Paramore.Brighter.Transformers.JustSaying/JsonConverters/IpAddressConverter.cs
  src/Paramore.Brighter.Transformers.JustSaying/JsonConverters/RegisterConverters.cs
  src/Paramore.Brighter.Transformers.JustSaying/JsonConverters/TenantConverter.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingAttribute.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingAttributesName.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingCommand.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingEvent.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingMessageMapper.cs
  src/Paramore.Brighter.Transformers.JustSaying/JustSayingTransform.cs
  src/Paramore.Brighter.Transformers.JustSaying/Paramore.Brighter.Transformers.JustSaying.csproj
  src/Paramore.Brighter.Transformers.JustSaying/Tenant.cs
  src/Paramore.Brighter.Transformers.MassTransit/Extensions/RequestContextExtensions.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitHeaderNames.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitMessageAttribute.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitMessageEnvelop.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitMessageMapper.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitTransform.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitUnwrapAttribute.cs
  src/Paramore.Brighter.Transformers.MassTransit/MassTransitWrapAttribute.cs
  src/Paramore.Brighter.Transformers.MassTransit/Paramore.Brighter.Transformers.MassTransit.csproj
  src/Paramore.Brighter/Id.cs
  src/Paramore.Brighter/Message.cs
  tests/Paramore.Brighter.Transforms.Adaptors.Tests/JustSaying/JustSayingMessageMapperTest.cs
  tests/Paramore.Brighter.Transforms.Adaptors.Tests/JustSaying/JustSayingTransformTest.cs
  tests/Paramore.Brighter.Transforms.Adaptors.Tests/MassTransit/MassTransitMessageMapperTest.cs
  tests/Paramore.Brighter.Transforms.Adaptors.Tests/MassTransit/MassTransitTransformTest.cs
  tests/Paramore.Brighter.Transforms.Adaptors.Tests/Paramore.Brighter.Transforms.Adaptors.Tests.csproj
Labels: 3 - Done, feature request, .NET, V10.X

#3672 Fix TimedOutboxArchiver calling only Archive async method
  src/Paramore.Brighter.Extensions.Hosting/TimedOutboxArchiver.cs
Labels: 3 - Done, v9, .NET, RC2

#3650 [Feature] Add support to Apache RocketMQ
  Brighter.sln
  Directory.Packages.props
  docker-compose-rocketmq.yaml
  src/Paramore.Brighter.MessagingGateway.RocketMQ/HeaderNames.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/Paramore.Brighter.MessagingGateway.RocketMQ.csproj
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessageConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessageProducerFactory.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessagingGatewayConnection.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqChannelFactory.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqPublication.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqSubscription.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessageDispatch/When_building_a_dispatcher.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessageDispatch/When_building_a_dispatcher_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessageDispatch/When_building_a_dispatcher_with_named_gateway.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_a_message_consumer_a_cloud_events_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_a_message_consumer_reads_multiple_messages_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_posting_a_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_requeueing_a_message_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_requeueing_redrives_to_the_dlq_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_a_message_consumer_a_cloud_events.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_a_message_consumer_reads_multiple_messages.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_requeueing_a_message.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_requeueing_redrives_to_the_dlq.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests.csproj
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyCommand.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyDeferredCommand.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyDeferredCommandHandler.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyDeferredCommandHandlerAsync.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyDeferredCommandMessageMapper.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyDeferredCommandMessageMapperAsync.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyEvent.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyEventMessageMapper.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/MyEventMessageMapperAsync.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/QuickHandlerFactory.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/TestDoubles/QuickHandlerFactoryAsync.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/Utils/GatewayFactory.cs
Labels: 2 - In Progress, feature request, .NET, V10.X

#3659 feat: Improve inbox and outbox
  src/Paramore.Brighter.Inbox.MsSql/MsSqlInbox.cs
  src/Paramore.Brighter.Inbox.MySql/MySqlInbox.cs
  src/Paramore.Brighter.Inbox.MySql/Paramore.Brighter.Inbox.MySql.csproj
  src/Paramore.Brighter.Inbox.Postgres/Paramore.Brighter.Inbox.Postgres.csproj
  src/Paramore.Brighter.Inbox.Postgres/PostgreSqlInbox.cs
  src/Paramore.Brighter.Inbox.Postgres/PostgreSqlQueries.cs
  src/Paramore.Brighter.Inbox.Sqlite/SqliteInbox.cs
  src/Paramore.Brighter.Inbox.Sqlite/SqliteQueries.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  src/Paramore.Brighter/RelationalDatabaseInbox.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_a_message_to_a_binary_body_outbox.cs
Labels: 3 - Done, Breaking Change, v10, .NET, RC2

#3651 [Feature] Support circuit breaking of topics
  Brighter.sln
  docs/adr/0028-support-circuit-breaking-of-topics.md
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  src/Paramore.Brighter.Outbox.DynamoDB.V4/DynamoDbOutbox.cs
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter.Outbox.Hosting/TimedOutboxSweeper.cs
  src/Paramore.Brighter.Outbox.MongoDb/MongoDbOutbox.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlQueries.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlQueries.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlQueries.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteQueries.cs
  src/Paramore.Brighter.ServiceActivator/ControlBus/ControlBusReceiverBuilder.cs
  src/Paramore.Brighter/CircuitBreaker/IAmAnOutboxCircuitBreaker.cs
  src/Paramore.Brighter/CircuitBreaker/InMemoryOutboxCircuitBreaker.cs
  src/Paramore.Brighter/CircuitBreaker/OutboxCircuitBreakerOptions.cs
  src/Paramore.Brighter/ControlBusSenderFactory.cs
  src/Paramore.Brighter/IAmAnOutboxAsync.cs
  src/Paramore.Brighter/IAmAnOutboxSync.cs
  src/Paramore.Brighter/IRelationDatabaseOutboxQueries.cs
  src/Paramore.Brighter/InMemoryOutbox.cs
  src/Paramore.Brighter/OutboxProducerMediator.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  tests/Paramore.Brighter.Core.Tests/CircuitBreaker/When_Cooldown_On_TrippedTopic.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Call/When_Calling_A_Server_Via_The_Command_Processor_With_No_Out_Mapper.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_Fails_Limit_Total_Writes_To_OutBox_In_Window.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_With_A_Default_Policy.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/SpyOutbox.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/When_there_are_outstanding_messages_in_the_outbox.cs
  tests/Paramore.Brighter.DynamoDB.V4.Tests/Outbox/When_there_are_outstanding_messages_in_the_outbox.cs
  tests/Paramore.Brighter.InMemory.Tests/Sweeper/When_sweeping_the_outbox_with_circuit_breaker.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/FailingMessageProducer.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
Labels: 2 - In Progress, feature request, v10, .NET, RC2
