Repository BrighterCommand/Brighter, pull requests merged in 2025-03, with the labels that each got.

#3549 Reduce dictionary lookups
  src/Paramore.Brighter.MessagingGateway.RMQ.Async/RmqMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.RMQ.Sync/RmqMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageConsumer.cs
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter/CommandProcessor.cs
  src/Paramore.Brighter/FeatureSwitch/Providers/FluentConfigRegistry.cs
  src/Paramore.Brighter/InMemoryLock.cs
  src/Paramore.Brighter/InternalBus.cs
  src/Paramore.Brighter/SubscriberRegistry.cs
Labels: 3 - Done, grabbed by community, v10, .NET, Performance Improvement

#3557 Add OTel to remaining outbox implementations
  samples/TaskQueue/ASBTaskQueue/GreetingsSender.Web/Program.cs
  samples/TaskQueue/MsSqlMessagingGateway/CompetingReceiverConsole/Program.cs
  samples/TaskQueue/MsSqlMessagingGateway/CompetingSender/Program.cs
  samples/TaskQueue/MsSqlMessagingGateway/GreetingsReceiverConsole/Program.cs
  samples/TaskQueue/MsSqlMessagingGateway/GreetingsSender/Program.cs
  samples/WebAPI/WebAPI_EFCore/SalutationAnalytics/Program.cs
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter.Outbox.MongoDb/MongoDbOutbox.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
  src/Paramore.Brighter/IAmARelationalDatabaseConfiguration.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  src/Paramore.Brighter/RelationalDatabaseConfiguration.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
Labels: 3 - Done, v10, .NET

#3556 Add support to CombinedChannelFactory.cs
  Brighter.sln
  docker-compose-rmq.yaml
  samples/TaskQueue/MultiBus/Greetings/Greetings.csproj
  samples/TaskQueue/MultiBus/Greetings/Ports/CommandHandlers/AnotherGreetingEventHandler.cs
  samples/TaskQueue/MultiBus/Greetings/Ports/CommandHandlers/GreetingEventHandler.cs
  samples/TaskQueue/MultiBus/Greetings/Ports/Commands/AnotherGreetingEvent.cs
  samples/TaskQueue/MultiBus/Greetings/Ports/Commands/GreetingEvent.cs
  samples/TaskQueue/MultiBus/Greetings/Ports/Mappers/AnotherGreetingEventMessageMapperAsync.cs
  samples/TaskQueue/MultiBus/Greetings/Ports/Mappers/GreetingEventMessageMapperAsync.cs
  samples/TaskQueue/MultiBus/Greetings/acceptance_test_message_body.txt
  samples/TaskQueue/MultiBus/GreetingsReceiverConsole/GreetingsReceiverConsole.csproj
  samples/TaskQueue/MultiBus/GreetingsReceiverConsole/Program.cs
  samples/TaskQueue/MultiBus/GreetingsReceiverConsole/appsettings.json
  samples/TaskQueue/MultiBus/GreetingsReceiverConsole/watch.txt
  samples/TaskQueue/MultiBus/GreetingsSender/GreetingsSender.csproj
  samples/TaskQueue/MultiBus/GreetingsSender/Program.cs
  samples/TaskQueue/MultiBus/GreetingsSender/Properties/launchSettings.json
  samples/TaskQueue/MultiBus/GreetingsSender/TimedMessageGenerator.cs
  samples/TaskQueue/MultiBus/GreetingsSender/appsettings.json
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsSubscription.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusSubscription.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaSubscription.cs
  src/Paramore.Brighter.MessagingGateway.MsSql/MsSqlSubscription.cs
  src/Paramore.Brighter.MessagingGateway.RMQ.Async/RmqSubscription.cs
  src/Paramore.Brighter.MessagingGateway.RMQ.Sync/RmqSubscription.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisSubscription.cs
  src/Paramore.Brighter/CombinedChannelFactory.cs
  src/Paramore.Brighter/Subscription.cs
  tests/Paramore.Brighter.Core.Tests/MessagingGateway/When_constructing_a_channel_with_combined_factory.cs
Labels: 2 - In Progress, feature request, v10, RC1
