Repository BrighterCommand/Brighter, pull requests merged in 2025-08, with the labels that each got.

#3689 feat: Update ServiceLifetime
  src/Paramore.Brighter.Extensions.DependencyInjection/BrighterOptions.cs
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
  tests/Paramore.Brighter.Extensions.Tests/AssemblyResolutionDefaultTransientTests.cs
  tests/Paramore.Brighter.Extensions.Tests/AssemblyResolutionHandlerLifetimeScopedAndMapperLifetimeSingletonTests.cs
Labels: 3 - Done, Bug, .NET, RC2

#3690 fix: Outbox Archive registration
  src/Paramore.Brighter.Outbox.Hosting/HostedServiceCollectionExtensions.cs
  src/Paramore.Brighter.Outbox.Hosting/TimedOutboxArchiver.cs
  src/Paramore.Brighter.Outbox.Hosting/TimedOutboxArchiverOptions.cs
Labels: 3 - Done, Bug, .NET, RC2

#3692 feat: Add support to tripped topics for MongoDB
  .github/workflows/ci.yml
  src/Paramore.Brighter.Outbox.MongoDb/MongoDbOutbox.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_messages_to_archive.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_messages_to_archive_async.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_outstanding_messages.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
Labels: 3 - Done, v10, .NET

#3688 feat: bulk dispatch to support circuit breaking
  docs/adr/0028-support-circuit-breaking-of-topics.md
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs
  src/Paramore.Brighter/IAmABulkMessageProducerAsync.cs
  src/Paramore.Brighter/IAmAMessageBatch.cs
  src/Paramore.Brighter/InMemoryMessageProducer.cs
  src/Paramore.Brighter/MessageBatch.cs
  src/Paramore.Brighter/OutboxProducerMediator.cs
  tests/Paramore.Brighter.InMemory.Tests/Sweeper/When_sweeping_the_outbox_with_circuit_breaker.cs
  tests/Paramore.Brighter.InMemory.Tests/TestDoubles/FailingMessageProducer.cs
Labels: 2 - In Progress, v10, .NET, RC2

#3696 fix: RocketMQ
  .github/workflows/ci.yml
  Brighter.sln
  docker-compose-rocketmq.yaml
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMessageProducerFactory.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.RocketMQ/RocketMqSubscription.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_a_message_consumer_a_cloud_events_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_posting_a_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_requeueing_a_message_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Proactor/When_requeueing_redrives_to_the_dlq_async.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_a_message_consumer_a_cloud_events.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_requeueing_a_message.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/MessagingGateway/Reactor/When_requeueing_redrives_to_the_dlq.cs
  tests/Paramore.Brighter.RocketMQ.Tests/Paramore.Brighter.RocketMQ.Tests/Utils/GatewayFactory.cs
Labels: 3 - Done, Bug, v10, RC2

#3693 Add Workflow Id and Job Id
  src/Paramore.Brighter.Outbox.DynamoDB.V4/MessageItem.cs
  src/Paramore.Brighter.Outbox.DynamoDB/MessageItem.cs
  src/Paramore.Brighter.Outbox.MongoDb/OutboxMessage.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlQueries.cs
  src/Paramore.Brighter.Outbox.MsSql/SqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlQueries.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlQueries.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteQueries.cs
  src/Paramore.Brighter/Extensions/RequestContextExtensions.cs
  src/Paramore.Brighter/MessageHeader.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  src/Paramore.Brighter/RequestContextBagNames.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_A_Message_To_The_Command_Processor.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_A_Message_To_The_Command_Processor_Async.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_A_Message_To_The_Command_Processor_With_A_Transaction_Provider.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_Multiple_Message_Types_To_A_Single_Topic.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_Multiple_Message_Types_To_A_Single_Topic_Async.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/MyCommandMessageMapper.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/TestDoubles/MyCommandMessageMapperAsync.cs
  tests/Paramore.Brighter.Core.Tests/Workflows/TestDoubles/MyOtherCommandMessageMapperAsync.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_a_message_to_the_message_store.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_a_message_to_the_message_store_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_a_message_to_the_message_store_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_a_message_to_the_outbox.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_Writing_A_Message_To_The_Outbox.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_Writing_A_Message_To_The_Outbox.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_Writing_A_Message_To_The_Outbox_Async.cs
Labels: 2 - In Progress, Breaking Change, feature request, v10, .NET, RC2

#3713 fix: Outbox registration when used with Sweeper & Archiver
  src/Paramore.Brighter.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
Labels: 3 - Done, Bug, v10

#3708 revert back to Microsoft.Data.SqlClient 6.0.2
  Directory.Packages.props
Labels: 3 - Done, dependencies, v10, .NET

#3710 Avoid linq Count()
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessageProducer.cs
  src/Paramore.Brighter.ServiceActivator.Extensions.Diagnostics/HealthChecks/BrighterServiceActivatorHealthCheck.cs
  src/Paramore.Brighter/OutboxArchiver.cs
  src/Paramore.Brighter/OutboxProducerMediator.cs
  src/Paramore.Brighter/PipelineBuilder.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Post/When_Posting_Fails_Limit_Total_Writes_To_OutBox_In_Window.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/Proactor/When_a_channel_failure_exception_is_thrown_for_command_should_retry_until_connection_re_established_async.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/Proactor/When_a_channel_failure_exception_is_thrown_for_event_should_retry_until_connection_re_established_async.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/Reactor/When_a_channel_failure_exception_is_thrown_for_command_should_retry_until_connection_re_established.cs
  tests/Paramore.Brighter.Core.Tests/MessageDispatch/Reactor/When_a_channel_failure_exception_is_thrown_for_event_should_retry_until_connection_re_established.cs
  tests/Paramore.Brighter.Core.Tests/Observability/CommandProcessor/Deposit/When_Depositing_Multiple_Requests_Spans_Are_Exported.cs
  tests/Paramore.Brighter.Core.Tests/Observability/CommandProcessor/Deposit/When_Depositing_Multiple_Requests_Spans_Are_Exported_Async.cs
  tests/Paramore.Brighter.InMemory.Tests/Outbox/When_Retrieving_Messages_based_on_Age.cs
  tests/Paramore.Brighter.InMemory.Tests/Outbox/When_storing_message_in_outbox.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_Removing_Messages_From_The_Outbox.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_removing_messages_from_the_outbox.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_there_are_multiple_outstanding_messages_in_the_outbox_and_messages_within_an_interval_are_fetched.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_Removing_Messages_From_The_Outbox.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_retrieving_messages_async.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_messages.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_messages_async.cs
Labels: 3 - Done, v10, .NET

#3714 mesages typo
  docs/guides/paramore_brighter_core_guide.md
Labels: 3 - Done, v10, Documentation

#3709 remove some redundant class bodies
  src/Paramore.Brighter.DynamoDb.V4/IAmADynamoDbTransactionProvider.cs
  src/Paramore.Brighter.DynamoDb/IAmADynamoDbTransactionProvider.cs
  src/Paramore.Brighter.MessagingGateway.MQTT/MQTTMessagingGatewayConfiguration.cs
  src/Paramore.Brighter.MessagingGateway.Postgres/PostgresQueries.cs
  src/Paramore.Brighter.MongoDb/IAmAMongoDbTransactionProvider.cs
  src/Paramore.Brighter/Actions/DeferMessageAction.cs
  src/Paramore.Brighter/BindingAttributes/DepositCallSiteAttribute.cs
  src/Paramore.Brighter/IAmAHandlerFactory.cs
  src/Paramore.Brighter/IAmAMessageMapper.cs
  src/Paramore.Brighter/IAmAMessageMapperAsync.cs
  src/Paramore.Brighter/IAmAMessageScheduler.cs
  src/Paramore.Brighter/IAmARequestScheduler.cs
  src/Paramore.Brighter/IAmATransactionConnectionProvider.cs
  src/Paramore.Brighter/IAmGatewayConfiguration.cs
  src/Paramore.Brighter/ICommand.cs
  src/Paramore.Brighter/IEvent.cs
  src/Paramore.Brighter/IResponse.cs
  src/Paramore.Brighter/Inbox/Attributes/NoGlobalInboxAttribute.cs
  src/Paramore.Brighter/Inbox/Exceptions/RequestNotFoundException.cs
  src/Paramore.Brighter/Polyfill/CompilerServices.cs
  tests/Paramore.Brighter.Core.Tests/CommandProcessors/Pipeline/When_There_Is_No_Sync_Or_Async_Handler_Factories.cs
  tests/Paramore.Brighter.DynamoDB.Tests/DynamoDbExtensions/When_Creating_A_Table_From_A_Class_Missing_A_Hash_Key.cs
  tests/Paramore.Brighter.DynamoDB.Tests/DynamoDbExtensions/When_Creating_A_Table_From_A_Class_Missing_Table_Attribute.cs
  tests/Paramore.Brighter.DynamoDB.V4.Tests/DynamoDbExtensions/When_Creating_A_Table_From_A_Class_Missing_A_Hash_Key.cs
  tests/Paramore.Brighter.DynamoDB.V4.Tests/DynamoDbExtensions/When_Creating_A_Table_From_A_Class_Missing_Table_Attribute.cs
  tests/Paramore.Brighter.Extensions.Tests/TestEventHandler.cs
  tests/Paramore.Test.Helpers/Loggers/ITestOutputLogger.cs
Labels: 3 - Done, v10, .NET

#3742 Make `SqsSubscription` constructors public
  src/Paramore.Brighter.MessagingGateway.AWS.V4/SqsSubscription.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsSubscription.cs
Labels: 3 - Done, Bug, v10, .NET

#3751 Do not protect an explicit Clear with a SemaphoreSlim
  docs/adr/0031-support-agreement-dispatcher.md
  docs/adr/0032-remove-explicit-clear-lock.md
  src/Paramore.Brighter/OutboxProducerMediator.cs
Labels: 3 - Done, v9, .NET, Performance Improvement, V10.X
