Repository BrighterCommand/Brighter, pull requests merged in 2025-06, with the labels that each got.

#3623 Avoid looking up bag value and made some private methods static
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsInlineMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageCreator.cs
  src/Paramore.Brighter.Outbox.MongoDb/OutboxMessage.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
Labels: 3 - Done, v10, Performance Improvement, RC1

#3625 Utilize that SqlDataReaders currently return MemoryStream to avoid manual stream copy
  src/Paramore.Brighter.MessagingGateway.Postgres/PostgresMessageConsumer.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
Labels: 2 - In Progress, v10, .NET, Performance Improvement, RC1

#3627 Otel and Cloud Events Transports Fixes
  src/Paramore.Brighter.MessagingGateway.AWSSQS/SqsMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageCreator.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessageCreator.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Proactor/When_recieving_a_message_without_partition_key_header_async.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_converting_kafkaheader_to_brighterheader.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_posting_a_message.cs
Labels: 2 - In Progress, v10, .NET, RC1

#3628 Otel Transports
  src/Paramore.Brighter.MessagingGateway.Redis/HeaderNames.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessagePublisher.cs
  tests/Paramore.Brighter.Redis.Tests/MessagingGateway/When_parsing_a_good_redis_message_to_brighter.cs
Labels: 3 - Done, v10, .NET, RC1

#3629 Otel Transports
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMessagePublisher.cs
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMesssageCreator.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Fifo/Proactor/When_posting_a_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Fifo/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Standard/Proactor/When_posting_a_message_via_the_messaging_gateway_async.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Standard/Reactor/When_posting_a_message_via_the_messaging_gateway.cs
Labels: 2 - In Progress, v10, .NET, RC1

#3630 Otel Transports
  src/Paramore.Brighter.MessagingGateway.AzureServiceBus/AzureServiceBusMesssageCreator.cs
Labels: 2 - In Progress, v10, .NET, RC1

#3635 Improve test by adding colorful output and GHA logger
  .github/workflows/ci.yml
  Directory.Packages.props
  tests/Paramore.Brighter.AWS.Tests/Paramore.Brighter.AWS.Tests.csproj
  tests/Paramore.Brighter.AWSScheduler.Tests/Paramore.Brighter.AWSScheduler.Tests.csproj
  tests/Paramore.Brighter.Azure.Tests/Paramore.Brighter.Azure.Tests.csproj
  tests/Paramore.Brighter.AzureServiceBus.Tests/Paramore.Brighter.AzureServiceBus.Tests.csproj
  tests/Paramore.Brighter.Core.Tests/Paramore.Brighter.Core.Tests.csproj
  tests/Paramore.Brighter.DynamoDB.Tests/Paramore.Brighter.DynamoDB.Tests.csproj
  tests/Paramore.Brighter.Extensions.Tests/Paramore.Brighter.Extensions.Tests.csproj
  tests/Paramore.Brighter.Hangfire.Tests/Paramore.Brighter.Hangfire.Tests.csproj
  tests/Paramore.Brighter.InMemory.Tests/Paramore.Brighter.InMemory.Tests.csproj
  tests/Paramore.Brighter.Kafka.Tests/Paramore.Brighter.Kafka.Tests.csproj
  tests/Paramore.Brighter.MQTT.Tests/Paramore.Brighter.MQTT.Tests.csproj
  tests/Paramore.Brighter.MSSQL.Tests/Paramore.Brighter.MSSQL.Tests.csproj
  tests/Paramore.Brighter.MongoDb.Tests/Paramore.Brighter.MongoDb.Tests.csproj
  tests/Paramore.Brighter.MySQL.Tests/Paramore.Brighter.MySQL.Tests.csproj
  tests/Paramore.Brighter.PostgresSQL.Tests/Paramore.Brighter.PostgresSQL.Tests.csproj
  tests/Paramore.Brighter.Quartz.Tests/Paramore.Brighter.Quartz.Tests.csproj
  tests/Paramore.Brighter.RMQ.Async.Tests/Paramore.Brighter.RMQ.Async.Tests.csproj
  tests/Paramore.Brighter.RMQ.Sync.Tests/Paramore.Brighter.RMQ.Sync.Tests.csproj
  tests/Paramore.Brighter.Redis.Tests/Paramore.Brighter.Redis.Tests.csproj
  tests/Paramore.Brighter.Sqlite.Tests/Paramore.Brighter.Sqlite.Tests.csproj
Labels: 2 - In Progress, dependencies, feature request, v10, .NET, RC2

#3632 fix: AWS S3 claim-check
  .github/workflows/ci.yml
  src/Paramore.Brighter.Tranformers.AWS/S3LuggageOptions.cs
  src/Paramore.Brighter.Tranformers.AWS/S3LuggageStore.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/AWSClientFactory.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/CredentialsChain.cs
  tests/Paramore.Brighter.AWS.Tests/Helpers/GatewayFactory.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Fifo/Proactor/When_raw_message_delivery_disabled_async.cs
  tests/Paramore.Brighter.AWS.Tests/MessagingGateway/Sqs/Standard/Proactor/When_requeueing_redrives_to_the_dlq_async.cs
  tests/Paramore.Brighter.AWS.Tests/Transformers/When_creating_luggagestore_missing_parameters.cs
  tests/Paramore.Brighter.AWS.Tests/Transformers/When_unwrapping_a_large_message.cs
  tests/Paramore.Brighter.AWS.Tests/Transformers/When_uploading_luggage_to_S3.cs
  tests/Paramore.Brighter.AWS.Tests/Transformers/When_validating_a_luggage_store_exists.cs
  tests/Paramore.Brighter.AWS.Tests/Transformers/When_wrapping_a_large_message.cs
Labels: 2 - In Progress, Bug, v10, RC1

#3633 Otel Transports
  src/Paramore.Brighter.Inbox.MsSql/MsSqlInbox.cs
  src/Paramore.Brighter.Inbox.MySql/MySqlInbox.cs
  src/Paramore.Brighter.Inbox.Postgres/PostgreSqlInbox.cs
  src/Paramore.Brighter.Inbox.Sqlite/SqliteInbox.cs
  src/Paramore.Brighter.MessagingGateway.Redis/RedisMessagePublisher.cs
  src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs
  src/Paramore.Brighter.Outbox.DynamoDB/MessageItem.cs
  src/Paramore.Brighter.Outbox.MongoDb/MongoDbOutbox.cs
  src/Paramore.Brighter.Outbox.MongoDb/OutboxMessage.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlOutbox.cs
  src/Paramore.Brighter.Outbox.MsSql/MsSqlQueries.cs
  src/Paramore.Brighter.Outbox.MsSql/SqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutbox.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.MySql/MySqlQueries.cs
  src/Paramore.Brighter.Outbox.PostgreSql/Paramore.Brighter.Outbox.PostgreSql.csproj
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutbox.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlQueries.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutbox.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteOutboxBuilder.cs
  src/Paramore.Brighter.Outbox.Sqlite/SqliteQueries.cs
  src/Paramore.Brighter/Observability/Baggage.cs
  src/Paramore.Brighter/RelationDatabaseOutbox.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/MessageItemTests.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/When_deleting_a_message_in_the_outbox.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/When_writing_a_utf8_message_to_the_outbox.cs
  tests/Paramore.Brighter.DynamoDB.Tests/Outbox/When_writing_a_utf8_message_to_the_outbox_async.cs
  tests/Paramore.Brighter.MSSQL.Tests/Inbox/When_writing_a_message_to_the_inbox_async.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_a_message_to_the_message_store.cs
  tests/Paramore.Brighter.MSSQL.Tests/Outbox/When_writing_a_message_to_the_message_store_async.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_There_Is_No_Message_In_The_Sql_Outbox.cs
  tests/Paramore.Brighter.MongoDb.Tests/Outbox/When_Writing_A_Message_To_The_Outbox.cs
  tests/Paramore.Brighter.MySQL.Tests/Inbox/When_the_message_is_already_in_the_inbox_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Inbox/When_writing_a_message_to_the_command_store.cs
  tests/Paramore.Brighter.MySQL.Tests/Inbox/When_writing_a_message_to_the_inbox_async.cs
  tests/Paramore.Brighter.MySQL.Tests/Outbox/When_writing_a_message_to_the_outbox.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/Outbox/When_Writing_A_Message_To_The_Outbox.cs
  tests/Paramore.Brighter.PostgresSQL.Tests/PostgresSqlTestHelper.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_Writing_A_Message_To_The_Outbox.cs
  tests/Paramore.Brighter.Sqlite.Tests/Outbox/When_retrieving_outstanding_messages_async.cs
Labels: 2 - In Progress, v10, .NET, RC1

#3639 Provide a callback to set ConsumerConfig
  Contributing.md
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageProducer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessagingGateway.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaSubscription.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/When_using_a_consumer_config_hook.cs
Labels: 3 - Done, feature request, v9

#3640 feat: allow configuration of Kafka ConsumerConfig through a KafkaSubscription.cs callback
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumer.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaMessageConsumerFactory.cs
  src/Paramore.Brighter.MessagingGateway.Kafka/KafkaSubscription.cs
  tests/Paramore.Brighter.Kafka.Tests/MessagingGateway/Reactor/When_using_a_consumer_config_hook.cs
Labels: 3 - Done, .NET
